import type {
  Workspace,
  Team,
  User,
  Label,
  Cycle,
  Issue,
} from "./types"

export const workspace: Workspace = {
  id: "ws-1",
  name: "Sedrino",
}

export const teams: Team[] = [
  {
    id: "t-1",
    slug: "fasig-tipon",
    name: "Fasig-Tipon",
    identifier: "FAS",
    color: "purple",
  },
  {
    id: "t-2",
    slug: "sedrino",
    name: "Sedrino",
    identifier: "SED",
    color: "blue",
  },
  {
    id: "t-3",
    slug: "stallnote",
    name: "Stallnote",
    identifier: "STL",
    color: "green",
  },
]

export const users: User[] = [
  { id: "u-1", name: "Connor Cummings", initials: "CC" },
  { id: "u-2", name: "Zaid Albulbul", initials: "ZA" },
  { id: "u-3", name: "Maria Flores", initials: "MF" },
  { id: "u-4", name: "Alex Kim", initials: "AK" },
]

export const labels: Label[] = [
  { id: "l-1", name: "Website", color: "blue" },
  { id: "l-2", name: "Bug", color: "red" },
  { id: "l-3", name: "Feature", color: "green" },
  { id: "l-4", name: "Backend", color: "purple" },
]

export const cycles: Record<string, Cycle[]> = {
  "fasig-tipon": [
    {
      id: "c-100",
      name: "Cycle 100",
      number: 100,
      startDate: "2025-03-23",
      endDate: "2025-03-29",
      status: "active",
    },
    {
      id: "c-101",
      name: "Cycle 101",
      number: 101,
      startDate: "2025-03-30",
      endDate: "2025-04-05",
      status: "upcoming",
    },
  ],
  sedrino: [
    {
      id: "c-50",
      name: "Cycle 50",
      number: 50,
      startDate: "2025-03-23",
      endDate: "2025-03-29",
      status: "active",
    },
  ],
  stallnote: [],
}

export const issues: Record<string, Issue[]> = {
  "fasig-tipon": [
    {
      id: "i-1",
      identifier: "FAS-1788",
      title: "Inspections Changes",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[0]],
      cycleId: "c-100",
      createdAt: "2025-03-26T15:26:31Z",
      updatedAt: "2025-03-26T15:26:31Z",
    },
    {
      id: "i-2",
      identifier: "FAS-1785",
      title: "Copy Mailing List update",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[1]],
      cycleId: "c-100",
      createdAt: "2025-03-25T10:00:00Z",
      updatedAt: "2025-03-25T10:00:00Z",
    },
    {
      id: "i-3",
      identifier: "FAS-663",
      title: "Website",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [labels[0]],
      assignees: [],
      cycleId: "c-100",
      createdAt: "2025-01-15T10:00:00Z",
      updatedAt: "2025-01-15T10:00:00Z",
    },
    {
      id: "i-4",
      identifier: "FAS-1791",
      title: "Show upcoming insections for a horse on /edit-entry/inspections",
      status: "todo",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [],
      cycleId: "c-100",
      createdAt: "2025-03-27T10:00:00Z",
      updatedAt: "2025-03-27T10:00:00Z",
    },
    {
      id: "i-5",
      identifier: "FAS-1790",
      title: "Inspection Results CSV download updates",
      status: "todo",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [],
      cycleId: "c-100",
      createdAt: "2025-03-27T08:00:00Z",
      updatedAt: "2025-03-27T08:00:00Z",
    },
    {
      id: "i-6",
      identifier: "FAS-1708",
      title: "Activity Rankings",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [],
      cycleId: "c-100",
      createdAt: "2025-02-10T10:00:00Z",
      updatedAt: "2025-02-10T10:00:00Z",
    },
    {
      id: "i-7",
      identifier: "FAS-1745",
      title: "SSO with Auctic",
      status: "todo",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [],
      cycleId: "c-100",
      createdAt: "2025-03-06T10:00:00Z",
      updatedAt: "2025-03-06T10:00:00Z",
    },
    {
      id: "i-8",
      identifier: "FAS-1661",
      title: "Review /upload-content pages for issues",
      status: "todo",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[2]],
      cycleId: "c-100",
      createdAt: "2025-01-15T10:00:00Z",
      updatedAt: "2025-01-15T10:00:00Z",
    },
    {
      id: "i-9",
      identifier: "FAS-1771",
      title: "Cleanup contact info for Farm Location records for all farm locations",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[0]],
      cycleId: "c-100",
      createdAt: "2025-03-18T10:00:00Z",
      updatedAt: "2025-03-18T10:00:00Z",
    },
    {
      id: "i-10",
      identifier: "FAS-1573",
      title: "Allow consignors to add additional Email and SMS bid notification recipients for digital sales",
      status: "in-review",
      priority: "medium",
      priorityScore: 100,
      labels: [],
      assignees: [users[0]],
      cycleId: "c-100",
      createdAt: "2024-12-23T10:00:00Z",
      updatedAt: "2024-12-23T10:00:00Z",
    },
    {
      id: "i-11",
      identifier: "FAS-1776",
      title: "Bug on Change Owner Record/Add New",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [labels[1]],
      assignees: [users[1]],
      cycleId: "c-100",
      createdAt: "2025-03-20T10:00:00Z",
      updatedAt: "2025-03-20T10:00:00Z",
    },
    {
      id: "i-12",
      identifier: "FAS-1282",
      title: "New Users are getting the Inspector permission when they should not be.",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[2]],
      cycleId: "c-100",
      createdAt: "2025-08-01T10:00:00Z",
      updatedAt: "2025-08-01T10:00:00Z",
    },
    {
      id: "i-13",
      identifier: "FAS-1693",
      title: "Consignor Statements",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[0]],
      cycleId: "c-100",
      createdAt: "2025-02-02T10:00:00Z",
      updatedAt: "2025-02-02T10:00:00Z",
    },
    {
      id: "i-14",
      identifier: "FAS-1789",
      title: "On Manual Entry, if user has not saved and tries to navigate away, through \"You have Unsaved Changes\" pop-up like on edit-entry",
      status: "todo",
      priority: "high",
      priorityScore: 101,
      labels: [],
      assignees: [],
      cycleId: "c-101",
      createdAt: "2025-03-27T10:00:00Z",
      updatedAt: "2025-03-27T10:00:00Z",
    },
  ],
  sedrino: [
    {
      id: "i-20",
      identifier: "SED-101",
      title: "Update dashboard analytics",
      status: "in-progress",
      priority: "high",
      priorityScore: 100,
      labels: [],
      assignees: [users[3]],
      cycleId: "c-50",
      createdAt: "2025-03-25T10:00:00Z",
      updatedAt: "2025-03-25T10:00:00Z",
    },
    {
      id: "i-21",
      identifier: "SED-102",
      title: "Fix login redirect issue",
      status: "todo",
      priority: "medium",
      priorityScore: 80,
      labels: [labels[1]],
      assignees: [users[0]],
      cycleId: "c-50",
      createdAt: "2025-03-24T10:00:00Z",
      updatedAt: "2025-03-24T10:00:00Z",
    },
  ],
  stallnote: [],
}
