/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OrgSelectRouteImport } from './routes/org-select'
import { Route as DefaultRouteImport } from './routes/_default'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DefaultIndexRouteImport } from './routes/_default.index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as AuthSlugRouteRouteImport } from './routes/_auth/$slug/route'
import { Route as ApiInternalFeedbackAnalysisRouteImport } from './routes/api/internal/feedback-analysis'
import { Route as AuthSlugDashboardRouteImport } from './routes/_auth/$slug.dashboard'
import { Route as AuthSlugTicketsRouteRouteImport } from './routes/_auth/$slug/tickets/route'
import { Route as AuthSlugTicketsIndexRouteImport } from './routes/_auth/$slug/tickets/index'
import { Route as AuthSlugTicketsSettingsRouteImport } from './routes/_auth/$slug/tickets/settings'
import { Route as AuthSlugTicketsFeedbackRouteImport } from './routes/_auth/$slug/tickets/feedback'
import { Route as AuthSlugTicketsDashboardRouteImport } from './routes/_auth/$slug/tickets/dashboard'
import { Route as AuthSlugTicketsViewsRouteRouteImport } from './routes/_auth/$slug/tickets/views/route'
import { Route as AuthSlugTicketsTeamSlugRouteRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/route'
import { Route as AuthSlugTicketsViewsIndexRouteImport } from './routes/_auth/$slug/tickets/views/index'
import { Route as AuthSlugTicketsViewsViewIdRouteImport } from './routes/_auth/$slug/tickets/views/$viewId'
import { Route as AuthSlugTicketsTeamSlugIssuesRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/issues'
import { Route as AuthSlugTicketsTeamSlugCyclesRouteRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/cycles/route'
import { Route as AuthSlugTicketsTeamSlugIssueIssueIdRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/issue.$issueId'
import { Route as AuthSlugTicketsTeamSlugCyclesUpcomingRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/cycles/upcoming'
import { Route as AuthSlugTicketsTeamSlugCyclesCurrentRouteImport } from './routes/_auth/$slug/tickets/$teamSlug/cycles/current'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSelectRoute = OrgSelectRouteImport.update({
  id: '/org-select',
  path: '/org-select',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugRouteRoute = AuthSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiInternalFeedbackAnalysisRoute =
  ApiInternalFeedbackAnalysisRouteImport.update({
    id: '/api/internal/feedback-analysis',
    path: '/api/internal/feedback-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSlugDashboardRoute = AuthSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthSlugRouteRoute,
} as any)
const AuthSlugTicketsRouteRoute = AuthSlugTicketsRouteRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthSlugRouteRoute,
} as any)
const AuthSlugTicketsIndexRoute = AuthSlugTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSlugTicketsRouteRoute,
} as any)
const AuthSlugTicketsSettingsRoute = AuthSlugTicketsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthSlugTicketsRouteRoute,
} as any)
const AuthSlugTicketsFeedbackRoute = AuthSlugTicketsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthSlugTicketsRouteRoute,
} as any)
const AuthSlugTicketsDashboardRoute =
  AuthSlugTicketsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthSlugTicketsRouteRoute,
  } as any)
const AuthSlugTicketsViewsRouteRoute =
  AuthSlugTicketsViewsRouteRouteImport.update({
    id: '/views',
    path: '/views',
    getParentRoute: () => AuthSlugTicketsRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugRouteRoute =
  AuthSlugTicketsTeamSlugRouteRouteImport.update({
    id: '/$teamSlug',
    path: '/$teamSlug',
    getParentRoute: () => AuthSlugTicketsRouteRoute,
  } as any)
const AuthSlugTicketsViewsIndexRoute =
  AuthSlugTicketsViewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugTicketsViewsRouteRoute,
  } as any)
const AuthSlugTicketsViewsViewIdRoute =
  AuthSlugTicketsViewsViewIdRouteImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => AuthSlugTicketsViewsRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugIssuesRoute =
  AuthSlugTicketsTeamSlugIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthSlugTicketsTeamSlugRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugCyclesRouteRoute =
  AuthSlugTicketsTeamSlugCyclesRouteRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AuthSlugTicketsTeamSlugRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugIssueIssueIdRoute =
  AuthSlugTicketsTeamSlugIssueIssueIdRouteImport.update({
    id: '/issue/$issueId',
    path: '/issue/$issueId',
    getParentRoute: () => AuthSlugTicketsTeamSlugRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugCyclesUpcomingRoute =
  AuthSlugTicketsTeamSlugCyclesUpcomingRouteImport.update({
    id: '/upcoming',
    path: '/upcoming',
    getParentRoute: () => AuthSlugTicketsTeamSlugCyclesRouteRoute,
  } as any)
const AuthSlugTicketsTeamSlugCyclesCurrentRoute =
  AuthSlugTicketsTeamSlugCyclesCurrentRouteImport.update({
    id: '/current',
    path: '/current',
    getParentRoute: () => AuthSlugTicketsTeamSlugCyclesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/org-select': typeof OrgSelectRoute
  '/preview': typeof PreviewRoute
  '/sign-up': typeof SignUpRoute
  '/$slug': typeof AuthSlugRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-in/': typeof SignInIndexRoute
  '/$slug/tickets': typeof AuthSlugTicketsRouteRouteWithChildren
  '/$slug/dashboard': typeof AuthSlugDashboardRoute
  '/api/internal/feedback-analysis': typeof ApiInternalFeedbackAnalysisRoute
  '/$slug/tickets/$teamSlug': typeof AuthSlugTicketsTeamSlugRouteRouteWithChildren
  '/$slug/tickets/views': typeof AuthSlugTicketsViewsRouteRouteWithChildren
  '/$slug/tickets/dashboard': typeof AuthSlugTicketsDashboardRoute
  '/$slug/tickets/feedback': typeof AuthSlugTicketsFeedbackRoute
  '/$slug/tickets/settings': typeof AuthSlugTicketsSettingsRoute
  '/$slug/tickets/': typeof AuthSlugTicketsIndexRoute
  '/$slug/tickets/$teamSlug/cycles': typeof AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren
  '/$slug/tickets/$teamSlug/issues': typeof AuthSlugTicketsTeamSlugIssuesRoute
  '/$slug/tickets/views/$viewId': typeof AuthSlugTicketsViewsViewIdRoute
  '/$slug/tickets/views/': typeof AuthSlugTicketsViewsIndexRoute
  '/$slug/tickets/$teamSlug/cycles/current': typeof AuthSlugTicketsTeamSlugCyclesCurrentRoute
  '/$slug/tickets/$teamSlug/cycles/upcoming': typeof AuthSlugTicketsTeamSlugCyclesUpcomingRoute
  '/$slug/tickets/$teamSlug/issue/$issueId': typeof AuthSlugTicketsTeamSlugIssueIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof DefaultIndexRoute
  '/org-select': typeof OrgSelectRoute
  '/preview': typeof PreviewRoute
  '/sign-up': typeof SignUpRoute
  '/$slug': typeof AuthSlugRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-in': typeof SignInIndexRoute
  '/$slug/dashboard': typeof AuthSlugDashboardRoute
  '/api/internal/feedback-analysis': typeof ApiInternalFeedbackAnalysisRoute
  '/$slug/tickets/$teamSlug': typeof AuthSlugTicketsTeamSlugRouteRouteWithChildren
  '/$slug/tickets/dashboard': typeof AuthSlugTicketsDashboardRoute
  '/$slug/tickets/feedback': typeof AuthSlugTicketsFeedbackRoute
  '/$slug/tickets/settings': typeof AuthSlugTicketsSettingsRoute
  '/$slug/tickets': typeof AuthSlugTicketsIndexRoute
  '/$slug/tickets/$teamSlug/cycles': typeof AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren
  '/$slug/tickets/$teamSlug/issues': typeof AuthSlugTicketsTeamSlugIssuesRoute
  '/$slug/tickets/views/$viewId': typeof AuthSlugTicketsViewsViewIdRoute
  '/$slug/tickets/views': typeof AuthSlugTicketsViewsIndexRoute
  '/$slug/tickets/$teamSlug/cycles/current': typeof AuthSlugTicketsTeamSlugCyclesCurrentRoute
  '/$slug/tickets/$teamSlug/cycles/upcoming': typeof AuthSlugTicketsTeamSlugCyclesUpcomingRoute
  '/$slug/tickets/$teamSlug/issue/$issueId': typeof AuthSlugTicketsTeamSlugIssueIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_default': typeof DefaultRouteWithChildren
  '/org-select': typeof OrgSelectRoute
  '/preview': typeof PreviewRoute
  '/sign-up': typeof SignUpRoute
  '/_auth/$slug': typeof AuthSlugRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/_default/': typeof DefaultIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/_auth/$slug/tickets': typeof AuthSlugTicketsRouteRouteWithChildren
  '/_auth/$slug/dashboard': typeof AuthSlugDashboardRoute
  '/api/internal/feedback-analysis': typeof ApiInternalFeedbackAnalysisRoute
  '/_auth/$slug/tickets/$teamSlug': typeof AuthSlugTicketsTeamSlugRouteRouteWithChildren
  '/_auth/$slug/tickets/views': typeof AuthSlugTicketsViewsRouteRouteWithChildren
  '/_auth/$slug/tickets/dashboard': typeof AuthSlugTicketsDashboardRoute
  '/_auth/$slug/tickets/feedback': typeof AuthSlugTicketsFeedbackRoute
  '/_auth/$slug/tickets/settings': typeof AuthSlugTicketsSettingsRoute
  '/_auth/$slug/tickets/': typeof AuthSlugTicketsIndexRoute
  '/_auth/$slug/tickets/$teamSlug/cycles': typeof AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren
  '/_auth/$slug/tickets/$teamSlug/issues': typeof AuthSlugTicketsTeamSlugIssuesRoute
  '/_auth/$slug/tickets/views/$viewId': typeof AuthSlugTicketsViewsViewIdRoute
  '/_auth/$slug/tickets/views/': typeof AuthSlugTicketsViewsIndexRoute
  '/_auth/$slug/tickets/$teamSlug/cycles/current': typeof AuthSlugTicketsTeamSlugCyclesCurrentRoute
  '/_auth/$slug/tickets/$teamSlug/cycles/upcoming': typeof AuthSlugTicketsTeamSlugCyclesUpcomingRoute
  '/_auth/$slug/tickets/$teamSlug/issue/$issueId': typeof AuthSlugTicketsTeamSlugIssueIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org-select'
    | '/preview'
    | '/sign-up'
    | '/$slug'
    | '/sign-in/$'
    | '/sign-in/'
    | '/$slug/tickets'
    | '/$slug/dashboard'
    | '/api/internal/feedback-analysis'
    | '/$slug/tickets/$teamSlug'
    | '/$slug/tickets/views'
    | '/$slug/tickets/dashboard'
    | '/$slug/tickets/feedback'
    | '/$slug/tickets/settings'
    | '/$slug/tickets/'
    | '/$slug/tickets/$teamSlug/cycles'
    | '/$slug/tickets/$teamSlug/issues'
    | '/$slug/tickets/views/$viewId'
    | '/$slug/tickets/views/'
    | '/$slug/tickets/$teamSlug/cycles/current'
    | '/$slug/tickets/$teamSlug/cycles/upcoming'
    | '/$slug/tickets/$teamSlug/issue/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/org-select'
    | '/preview'
    | '/sign-up'
    | '/$slug'
    | '/sign-in/$'
    | '/sign-in'
    | '/$slug/dashboard'
    | '/api/internal/feedback-analysis'
    | '/$slug/tickets/$teamSlug'
    | '/$slug/tickets/dashboard'
    | '/$slug/tickets/feedback'
    | '/$slug/tickets/settings'
    | '/$slug/tickets'
    | '/$slug/tickets/$teamSlug/cycles'
    | '/$slug/tickets/$teamSlug/issues'
    | '/$slug/tickets/views/$viewId'
    | '/$slug/tickets/views'
    | '/$slug/tickets/$teamSlug/cycles/current'
    | '/$slug/tickets/$teamSlug/cycles/upcoming'
    | '/$slug/tickets/$teamSlug/issue/$issueId'
  id:
    | '__root__'
    | '/_auth'
    | '/_default'
    | '/org-select'
    | '/preview'
    | '/sign-up'
    | '/_auth/$slug'
    | '/sign-in/$'
    | '/_default/'
    | '/sign-in/'
    | '/_auth/$slug/tickets'
    | '/_auth/$slug/dashboard'
    | '/api/internal/feedback-analysis'
    | '/_auth/$slug/tickets/$teamSlug'
    | '/_auth/$slug/tickets/views'
    | '/_auth/$slug/tickets/dashboard'
    | '/_auth/$slug/tickets/feedback'
    | '/_auth/$slug/tickets/settings'
    | '/_auth/$slug/tickets/'
    | '/_auth/$slug/tickets/$teamSlug/cycles'
    | '/_auth/$slug/tickets/$teamSlug/issues'
    | '/_auth/$slug/tickets/views/$viewId'
    | '/_auth/$slug/tickets/views/'
    | '/_auth/$slug/tickets/$teamSlug/cycles/current'
    | '/_auth/$slug/tickets/$teamSlug/cycles/upcoming'
    | '/_auth/$slug/tickets/$teamSlug/issue/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DefaultRoute: typeof DefaultRouteWithChildren
  OrgSelectRoute: typeof OrgSelectRoute
  PreviewRoute: typeof PreviewRoute
  SignUpRoute: typeof SignUpRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiInternalFeedbackAnalysisRoute: typeof ApiInternalFeedbackAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-select': {
      id: '/org-select'
      path: '/org-select'
      fullPath: '/org-select'
      preLoaderRoute: typeof OrgSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug': {
      id: '/_auth/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/internal/feedback-analysis': {
      id: '/api/internal/feedback-analysis'
      path: '/api/internal/feedback-analysis'
      fullPath: '/api/internal/feedback-analysis'
      preLoaderRoute: typeof ApiInternalFeedbackAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/dashboard': {
      id: '/_auth/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/$slug/dashboard'
      preLoaderRoute: typeof AuthSlugDashboardRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/tickets': {
      id: '/_auth/$slug/tickets'
      path: '/tickets'
      fullPath: '/$slug/tickets'
      preLoaderRoute: typeof AuthSlugTicketsRouteRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/tickets/': {
      id: '/_auth/$slug/tickets/'
      path: '/'
      fullPath: '/$slug/tickets/'
      preLoaderRoute: typeof AuthSlugTicketsIndexRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/settings': {
      id: '/_auth/$slug/tickets/settings'
      path: '/settings'
      fullPath: '/$slug/tickets/settings'
      preLoaderRoute: typeof AuthSlugTicketsSettingsRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/feedback': {
      id: '/_auth/$slug/tickets/feedback'
      path: '/feedback'
      fullPath: '/$slug/tickets/feedback'
      preLoaderRoute: typeof AuthSlugTicketsFeedbackRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/dashboard': {
      id: '/_auth/$slug/tickets/dashboard'
      path: '/dashboard'
      fullPath: '/$slug/tickets/dashboard'
      preLoaderRoute: typeof AuthSlugTicketsDashboardRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/views': {
      id: '/_auth/$slug/tickets/views'
      path: '/views'
      fullPath: '/$slug/tickets/views'
      preLoaderRoute: typeof AuthSlugTicketsViewsRouteRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug': {
      id: '/_auth/$slug/tickets/$teamSlug'
      path: '/$teamSlug'
      fullPath: '/$slug/tickets/$teamSlug'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugRouteRouteImport
      parentRoute: typeof AuthSlugTicketsRouteRoute
    }
    '/_auth/$slug/tickets/views/': {
      id: '/_auth/$slug/tickets/views/'
      path: '/'
      fullPath: '/$slug/tickets/views/'
      preLoaderRoute: typeof AuthSlugTicketsViewsIndexRouteImport
      parentRoute: typeof AuthSlugTicketsViewsRouteRoute
    }
    '/_auth/$slug/tickets/views/$viewId': {
      id: '/_auth/$slug/tickets/views/$viewId'
      path: '/$viewId'
      fullPath: '/$slug/tickets/views/$viewId'
      preLoaderRoute: typeof AuthSlugTicketsViewsViewIdRouteImport
      parentRoute: typeof AuthSlugTicketsViewsRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug/issues': {
      id: '/_auth/$slug/tickets/$teamSlug/issues'
      path: '/issues'
      fullPath: '/$slug/tickets/$teamSlug/issues'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugIssuesRouteImport
      parentRoute: typeof AuthSlugTicketsTeamSlugRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug/cycles': {
      id: '/_auth/$slug/tickets/$teamSlug/cycles'
      path: '/cycles'
      fullPath: '/$slug/tickets/$teamSlug/cycles'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugCyclesRouteRouteImport
      parentRoute: typeof AuthSlugTicketsTeamSlugRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug/issue/$issueId': {
      id: '/_auth/$slug/tickets/$teamSlug/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/$slug/tickets/$teamSlug/issue/$issueId'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugIssueIssueIdRouteImport
      parentRoute: typeof AuthSlugTicketsTeamSlugRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug/cycles/upcoming': {
      id: '/_auth/$slug/tickets/$teamSlug/cycles/upcoming'
      path: '/upcoming'
      fullPath: '/$slug/tickets/$teamSlug/cycles/upcoming'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugCyclesUpcomingRouteImport
      parentRoute: typeof AuthSlugTicketsTeamSlugCyclesRouteRoute
    }
    '/_auth/$slug/tickets/$teamSlug/cycles/current': {
      id: '/_auth/$slug/tickets/$teamSlug/cycles/current'
      path: '/current'
      fullPath: '/$slug/tickets/$teamSlug/cycles/current'
      preLoaderRoute: typeof AuthSlugTicketsTeamSlugCyclesCurrentRouteImport
      parentRoute: typeof AuthSlugTicketsTeamSlugCyclesRouteRoute
    }
  }
}

interface AuthSlugTicketsTeamSlugCyclesRouteRouteChildren {
  AuthSlugTicketsTeamSlugCyclesCurrentRoute: typeof AuthSlugTicketsTeamSlugCyclesCurrentRoute
  AuthSlugTicketsTeamSlugCyclesUpcomingRoute: typeof AuthSlugTicketsTeamSlugCyclesUpcomingRoute
}

const AuthSlugTicketsTeamSlugCyclesRouteRouteChildren: AuthSlugTicketsTeamSlugCyclesRouteRouteChildren =
  {
    AuthSlugTicketsTeamSlugCyclesCurrentRoute:
      AuthSlugTicketsTeamSlugCyclesCurrentRoute,
    AuthSlugTicketsTeamSlugCyclesUpcomingRoute:
      AuthSlugTicketsTeamSlugCyclesUpcomingRoute,
  }

const AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren =
  AuthSlugTicketsTeamSlugCyclesRouteRoute._addFileChildren(
    AuthSlugTicketsTeamSlugCyclesRouteRouteChildren,
  )

interface AuthSlugTicketsTeamSlugRouteRouteChildren {
  AuthSlugTicketsTeamSlugCyclesRouteRoute: typeof AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren
  AuthSlugTicketsTeamSlugIssuesRoute: typeof AuthSlugTicketsTeamSlugIssuesRoute
  AuthSlugTicketsTeamSlugIssueIssueIdRoute: typeof AuthSlugTicketsTeamSlugIssueIssueIdRoute
}

const AuthSlugTicketsTeamSlugRouteRouteChildren: AuthSlugTicketsTeamSlugRouteRouteChildren =
  {
    AuthSlugTicketsTeamSlugCyclesRouteRoute:
      AuthSlugTicketsTeamSlugCyclesRouteRouteWithChildren,
    AuthSlugTicketsTeamSlugIssuesRoute: AuthSlugTicketsTeamSlugIssuesRoute,
    AuthSlugTicketsTeamSlugIssueIssueIdRoute:
      AuthSlugTicketsTeamSlugIssueIssueIdRoute,
  }

const AuthSlugTicketsTeamSlugRouteRouteWithChildren =
  AuthSlugTicketsTeamSlugRouteRoute._addFileChildren(
    AuthSlugTicketsTeamSlugRouteRouteChildren,
  )

interface AuthSlugTicketsViewsRouteRouteChildren {
  AuthSlugTicketsViewsViewIdRoute: typeof AuthSlugTicketsViewsViewIdRoute
  AuthSlugTicketsViewsIndexRoute: typeof AuthSlugTicketsViewsIndexRoute
}

const AuthSlugTicketsViewsRouteRouteChildren: AuthSlugTicketsViewsRouteRouteChildren =
  {
    AuthSlugTicketsViewsViewIdRoute: AuthSlugTicketsViewsViewIdRoute,
    AuthSlugTicketsViewsIndexRoute: AuthSlugTicketsViewsIndexRoute,
  }

const AuthSlugTicketsViewsRouteRouteWithChildren =
  AuthSlugTicketsViewsRouteRoute._addFileChildren(
    AuthSlugTicketsViewsRouteRouteChildren,
  )

interface AuthSlugTicketsRouteRouteChildren {
  AuthSlugTicketsTeamSlugRouteRoute: typeof AuthSlugTicketsTeamSlugRouteRouteWithChildren
  AuthSlugTicketsViewsRouteRoute: typeof AuthSlugTicketsViewsRouteRouteWithChildren
  AuthSlugTicketsDashboardRoute: typeof AuthSlugTicketsDashboardRoute
  AuthSlugTicketsFeedbackRoute: typeof AuthSlugTicketsFeedbackRoute
  AuthSlugTicketsSettingsRoute: typeof AuthSlugTicketsSettingsRoute
  AuthSlugTicketsIndexRoute: typeof AuthSlugTicketsIndexRoute
}

const AuthSlugTicketsRouteRouteChildren: AuthSlugTicketsRouteRouteChildren = {
  AuthSlugTicketsTeamSlugRouteRoute:
    AuthSlugTicketsTeamSlugRouteRouteWithChildren,
  AuthSlugTicketsViewsRouteRoute: AuthSlugTicketsViewsRouteRouteWithChildren,
  AuthSlugTicketsDashboardRoute: AuthSlugTicketsDashboardRoute,
  AuthSlugTicketsFeedbackRoute: AuthSlugTicketsFeedbackRoute,
  AuthSlugTicketsSettingsRoute: AuthSlugTicketsSettingsRoute,
  AuthSlugTicketsIndexRoute: AuthSlugTicketsIndexRoute,
}

const AuthSlugTicketsRouteRouteWithChildren =
  AuthSlugTicketsRouteRoute._addFileChildren(AuthSlugTicketsRouteRouteChildren)

interface AuthSlugRouteRouteChildren {
  AuthSlugTicketsRouteRoute: typeof AuthSlugTicketsRouteRouteWithChildren
  AuthSlugDashboardRoute: typeof AuthSlugDashboardRoute
}

const AuthSlugRouteRouteChildren: AuthSlugRouteRouteChildren = {
  AuthSlugTicketsRouteRoute: AuthSlugTicketsRouteRouteWithChildren,
  AuthSlugDashboardRoute: AuthSlugDashboardRoute,
}

const AuthSlugRouteRouteWithChildren = AuthSlugRouteRoute._addFileChildren(
  AuthSlugRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSlugRouteRoute: typeof AuthSlugRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSlugRouteRoute: AuthSlugRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DefaultRouteChildren {
  DefaultIndexRoute: typeof DefaultIndexRoute
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultIndexRoute: DefaultIndexRoute,
}

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
  OrgSelectRoute: OrgSelectRoute,
  PreviewRoute: PreviewRoute,
  SignUpRoute: SignUpRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiInternalFeedbackAnalysisRoute: ApiInternalFeedbackAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
